services:
  repository-1:
    build:
      context: ./
    ports:
      - "4002:4002"
      - "8000:8000"
    environment:
      - PORT=8000
      - ORBITDB_PORT=4002
    depends_on:
      - ipfs

  repository-2:
    build:
      context: ./
    ports:
      - "4003:4003"
      - "8001:8001"
    environment:
      - PORT=8001
      - ORBITDB_PORT=4003
    depends_on:
      - ipfs

  repository-3:
    build:
      context: ./
    ports:
      - "4004:4004"
      - "8002:8002"
    environment:
      - PORT=8002
      - ORBITDB_PORT=4004
    depends_on:
      - ipfs

  ipfs:
    image: ipfs/kubo:latest
    ports:
      - "5001:5001"
      - "8080:8080"
      - "4001:4001"
